name: cellberta
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - transformers
  - datasets
  - huggingface_hub
  - evaluate
  - pip
  - pydantic
  - python-dotenv
  - black
  - isort
  - tqdm
  - wandb
  - pandas
  - matplotlib
  - seaborn
  - accelerate
  - scikit-learn
  - scipy
  - jupyter
  - pillow
  - pip:
    - deepspeed
    - peft
    - rdkit
    - huggingface_mae